# Generated by Django 5.0.2 on 2024-03-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migraine_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='migraineaanval',
            name='medicijnen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='symptoom',
            name='naam',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='naam',
            field=models.CharField(max_length=100),
        ),
    ]
