# Generated by Django 5.0.2 on 2024-02-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(choices=[('Hoofdpijn', 'Hoofdpijn'), ('Misselijkheid', 'Misselijkheid'), ('Duizeligheid', 'Duizeligheid')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(choices=[('Stress', 'Stress'), ('Cafeïne', 'Cafeïne'), ('Veranderingen in het weer', 'Veranderingen in het weer')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MigraineAanval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('pijn_score', models.IntegerField()),
                ('notities', models.TextField(blank=True, null=True)),
                ('symptomen', models.ManyToManyField(related_name='migraine_aanvallen', to='migraine_tracker.symptoom')),
                ('triggers', models.ManyToManyField(related_name='migraine_aanvallen', to='migraine_tracker.trigger')),
            ],
        ),
    ]
